-- Data for `product_category` table
INSERT INTO product_category (id, name) VALUES (1, 'CDs');
INSERT INTO product_category (id, name) VALUES (2, 'Books');
INSERT INTO product_category (id, name) VALUES (3, 'Books Accessories');
INSERT INTO product_category (id, name) VALUES (4, 'eBooks');
INSERT INTO product_category (id, name) VALUES (5, 'Electronics');
INSERT INTO product_category (id, name) VALUES (6, 'Electronics Accessories');
INSERT INTO product_category (id, name) VALUES (7, 'Cameras');
INSERT INTO product_category (id, name) VALUES (8, 'Vehicle Electronics');
INSERT INTO product_category (id, name) VALUES (9, 'Cell Phones');
INSERT INTO product_category (id, name) VALUES (10, 'Cell Phones Accessories');
INSERT INTO product_category (id, name) VALUES (11, 'Computer');
INSERT INTO product_category (id, name) VALUES (12, 'Computer Accessories');
INSERT INTO product_category (id, name) VALUES (13, 'GPS');
INSERT INTO product_category (id, name) VALUES (14, 'Headphones');
INSERT INTO product_category (id, name) VALUES (15, 'Home Audio');
INSERT INTO product_category (id, name) VALUES (16, 'Office Eletronics');
INSERT INTO product_category (id, name) VALUES (17, 'Portable Audio');
INSERT INTO product_category (id, name) VALUES (18, 'Portable Video');
INSERT INTO product_category (id, name) VALUES (19, 'Electronics Security');
INSERT INTO product_category (id, name) VALUES (20, 'Service Plans');
INSERT INTO product_category (id, name) VALUES (21, 'Televisions');
INSERT INTO product_category (id, name) VALUES (22, 'Video Game Consoles');
INSERT INTO product_category (id, name) VALUES (23, 'Video Game Accessories');
INSERT INTO product_category (id, name) VALUES (24, 'Video Projectors');
INSERT INTO product_category (id, name) VALUES (25, 'Wearable Technology');
INSERT INTO product_category (id, name) VALUES (26, 'eBook Readers');
INSERT INTO product_category (id, name) VALUES (27, 'eBook Accessories');
INSERT INTO product_category (id, name) VALUES (28, 'Computer Components');
INSERT INTO product_category (id, name) VALUES (29, 'Tablets');
INSERT INTO product_category (id, name) VALUES (30, 'Data Storage');
INSERT INTO product_category (id, name) VALUES (31, 'External Components');
INSERT INTO product_category (id, name) VALUES (32, 'Laptop Accessories');
INSERT INTO product_category (id, name) VALUES (33, 'Monitors');
INSERT INTO product_category (id, name) VALUES (34, 'Networking Products');
INSERT INTO product_category (id, name) VALUES (35, 'Power Strips');
INSERT INTO product_category (id, name) VALUES (36, 'Printers');
INSERT INTO product_category (id, name) VALUES (37, 'Scanners');
INSERT INTO product_category (id, name) VALUES (38, 'Servers');
INSERT INTO product_category (id, name) VALUES (39, 'Tablet Accessories');
INSERT INTO product_category (id, name) VALUES (40, 'Tablet Replacement Parts');
INSERT INTO product_category (id, name) VALUES (41, 'Maintenence Services');
INSERT INTO product_category (id, name) VALUES (42, 'Lightning');
INSERT INTO product_category (id, name) VALUES (43, 'Door Locks');
INSERT INTO product_category (id, name) VALUES (44, 'Plugs');
INSERT INTO product_category (id, name) VALUES (45, 'Other Smart Solutions');
INSERT INTO product_category (id, name) VALUES (46, 'Thermostats');
INSERT INTO product_category (id, name) VALUES (47, 'Security Systems');
INSERT INTO product_category (id, name) VALUES (48, 'Speakers');
INSERT INTO product_category (id, name) VALUES (49, 'Voice Assistants');
INSERT INTO product_category (id, name) VALUES (50, 'Kitchen');
INSERT INTO product_category (id, name) VALUES (51, 'Vaccums');
INSERT INTO product_category (id, name) VALUES (52, 'Network');
INSERT INTO product_category (id, name) VALUES (53, 'Wifi');
INSERT INTO product_category (id, name) VALUES (54, 'Painting');
INSERT INTO product_category (id, name) VALUES (55, 'Art Supplies');
INSERT INTO product_category (id, name) VALUES (56, 'Jewelry');
INSERT INTO product_category (id, name) VALUES (57, 'Crafting');
INSERT INTO product_category (id, name) VALUES (58, 'Fabric');
INSERT INTO product_category (id, name) VALUES (59, 'Fabric Decorating');
INSERT INTO product_category (id, name) VALUES (60, 'Crochet');
INSERT INTO product_category (id, name) VALUES (61, 'Needlework');
INSERT INTO product_category (id, name) VALUES (62, 'Printmaking');
INSERT INTO product_category (id, name) VALUES (63, 'Scrapbooking');
INSERT INTO product_category (id, name) VALUES (64, 'Sewing');
INSERT INTO product_category (id, name) VALUES (65, 'Party Decorations');
INSERT INTO product_category (id, name) VALUES (66, 'Party Supplies');
INSERT INTO product_category (id, name) VALUES (67, 'Gift Wrapping Supplies');
INSERT INTO product_category (id, name) VALUES (68, 'Car Care');
INSERT INTO product_category (id, name) VALUES (69, 'Car Electronics');
INSERT INTO product_category (id, name) VALUES (70, 'Car Accessories');
INSERT INTO product_category (id, name) VALUES (71, 'Automotive Exterior Accessories');
INSERT INTO product_category (id, name) VALUES (72, 'Automotive Interior Accessories');
INSERT INTO product_category (id, name) VALUES (73, 'Lighting Accessories');
INSERT INTO product_category (id, name) VALUES (74, 'Motorcycle');
INSERT INTO product_category (id, name) VALUES (75, 'Automotive Oils');
INSERT INTO product_category (id, name) VALUES (76, 'Automotive Paint');
INSERT INTO product_category (id, name) VALUES (77, 'Automotive Replacement Parts');
INSERT INTO product_category (id, name) VALUES (78, 'Wheels');
INSERT INTO product_category (id, name) VALUES (79, 'Baby Toys');
INSERT INTO product_category (id, name) VALUES (80, 'Baby Care');
INSERT INTO product_category (id, name) VALUES (81, 'Pregnancy');
INSERT INTO product_category (id, name) VALUES (82, 'Makeup');
INSERT INTO product_category (id, name) VALUES (83, 'Skin Care');
INSERT INTO product_category (id, name) VALUES (84, 'Hair Care');
INSERT INTO product_category (id, name) VALUES (85, 'Fragrance');
INSERT INTO product_category (id, name) VALUES (86, 'Clothing');
INSERT INTO product_category (id, name) VALUES (87, 'Shoes');
INSERT INTO product_category (id, name) VALUES (88, 'Watches');
INSERT INTO product_category (id, name) VALUES (89, 'Bath');
INSERT INTO product_category (id, name) VALUES (90, 'Wall Art');
INSERT INTO product_category (id, name) VALUES (91, 'Cleaning Supplies');
INSERT INTO product_category (id, name) VALUES (92, 'Movies');
INSERT INTO product_category (id, name) VALUES (93, 'Dogs');
INSERT INTO product_category (id, name) VALUES (94, 'Cats');
INSERT INTO product_category (id, name) VALUES (95, 'Fish');
INSERT INTO product_category (id, name) VALUES (96, 'Birds');
INSERT INTO product_category (id, name) VALUES (97, 'Sports');
INSERT INTO product_category (id, name) VALUES (98, 'Fitness');
INSERT INTO product_category (id, name) VALUES (99, 'Games');
INSERT INTO product_category (id, name) VALUES (100, 'Puzzles');